name: Notebook
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decrypt google-services.json
        env:
          FIREBASE_SECRET: ${{secrets.FIREBASE_SECRET}}
        run: echo $FIREBASE_SECRET > app/google-services.json
      - name: Run Unit Test
        run: ./gradlew test
      - name: Build Project
        run: ./gradlew assemble

  instrumented-tests:
    runs-on: macOS-latest
    strategy:
      fail-fast: true
      matrix:
        api-level: [21, 29, 30]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decrypt google-services.json
        env:
          FIREBASE_SECRET: ${{secrets.FIREBASE_SECRET}}
        run: echo $FIREBASE_SECRET > app/google-services.json
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          script: ./gradlew connectedDebugAndroidTest